### ISSUE TITLE
[feature request] Right click should "downgrade" item

### ISSUE THREAD

**Issue by Simn** [Loogaroo1/ALTTP-RandoTracker#2]
Right now, both left and right click share the same functionality. It would be nice if a right click would do the opposite of a left click. For instance, if you have Titan's Mitts activated, right click should change it to Power Gloves, and another right click should change it back to nothing.

**Comment by Loogaroo1** [comment]
Right-clicks should already downgrade any items with progressive tiers (swords/bow/glove/etc.), as well as reverse increments on dungeon exploration. You may be using an older version of the tracker if this is an issue.

**Comment by Loogaroo1** [comment]
OK, so it appears that the right-click functionality was not added to gloves or boomerangs. I'll fix that later tonight.

**Comment by Loogaroo1** [comment]
Latest update fixes this issue.
