### ISSUE TITLE
[feature request] Reset button

### ISSUE THREAD

**Issue by Simn** [Loogaroo1/ALTTP-RandoTracker#3]
There doesn't seem to be one. :)

**Comment by Loogaroo1** [comment]
There isn't one, mainly because I've always found it easier to just close/reopen the tracker than reset the 200+ variables and controls in the app. I actually had a reset button in an earlier version that just popped up a dialog that said "LOL. Just close and reopen."

**Comment by Loogaroo1** [comment]
Reset button has been added as of version 1.1.
