### ISSUE TITLE
Spike Cave is shown as available,  but I don't have the power glove.

### ISSUE THREAD

**Issue by CaseyNovo** [Loogaroo1/ALTTP-RandoTracker#4]
I have the cape, 1/2 magic, and the hammer, but no power glove to pick up the block at the end of Spike Cave, but the tracker says it is available. 
![image](https://user-images.githubusercontent.com/11916101/39560274-bac40222-4e6a-11e8-882a-ba39f4818bda.png)

**Comment by Loogaroo1** [comment]
Good catch. Glove was in the logic when you didn't have safeties (as a sequence break) but not when you did. Fixed in upcoming update.

Also, expect the font issues with the dungeon labels to be fixed as well.
