### ISSUE TITLE
POD Keysanity Issue & potentially TR Swordless Issue

### ISSUE THREAD

**Issue by Keaen** [Loogaroo1/ALTTP-RandoTracker#6]
POD is always yellow or red regardless of Items or Key amount, In addition it is impossible to "clear" the boss while at any key number besides 1. This is for both with and without swords.

In addition while looking at this I noticed that in Keysanity Swordless TR remains red despite having every item and all other locations checked.

**Comment by Jaylow7** [comment]
I have also noticed this behavior with PoD in Keysanity mode.  

In a run I did this evening the inability to mark PoD as complete caused other parts of the tracker's logic to fail, as PoD was a Pyramid Fairy crystal, so the tracker didn't recognize I could check that location or actually had logical access to GT (was still red despite having cleared all crystal dungeons)

**Comment by Loogaroo1** [comment]
Sorry about that; the POD check had a Glove = True check instead of Glove > 0, which meant that the only way POD would go Green/Orange is if Aganhim was defeated. Resolved in new version.
